name: Deploy Flask App to Windows Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.3'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Kill existing process
      run: |
        Stop-Process -Name "python" -Force -ErrorAction SilentlyContinue
    
    - name: Run Flask app
      run: |
        $env:FLASK_APP = "app.py"
        Start-Process python -ArgumentList "-m flask run --host=0.0.0.0 --port=5000" -NoNewWindow